#!/bin/sh
if [ $# -eq 1 ]
then
  ppa_name=`echo "$1" | cut -d ":" -f2-`

  if [ -z "$ppa_name" ]
  then
    echo "PPA name not found"
    echo "Utility to add PPA repositories in your debian machine"
    echo "$0/ppa ppa: user-name"
  else
    echo "$ppa_name"
    echo "deb http://ppa.launchpad.net/$ppa_name/ubuntu maverick main" >> /etc/apt/sources.list
    apt-get update > /dev/null 2>> /tmp/apt_add_key.txt
    key=`cat /tmp/apt_add_key.txt | cut -d ""-f6 | cut -d"" -f3`
    apt-key adv-keyserver keyserver.ubuntu.com-recv-keys $key
    rm -rf /tmp/apt_add_key.txt
  fi
else
  echo "Utility to add PPA repositories in your debian machine"
  echo "$0/ppa ppa: user-name"
fi

#保存这个脚本到/usr/bin目录下，名称为add-apt-repository，然后执行下列命令即可：
#  $ sudo chmod +x /usr/bin/add-apt-repository
#  $ sudo chown root:root /usr/bin/add-apt-repository

# 使用
# $ sudo add-apt-repository ppa: name
# 或者ubuntu下直接安装python-software-properties
